version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    tty: true
    volumes:
      - .:/work
    ports:
      - 8001:8001
    depends_on:
      - postgres
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env

  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    depends_on:
      - postgres
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
  # front:
  #   build:
  #     context: .
  #     dockerfile: containers/react/Dockerfile
  #   restart: always
  #   volumes:
  #     - ./node:/usr/src/app:cached
  #   command: sh -c "cd KawakeraProject && yarn start"
  #   ports:
  #     - "3000:3000"


volumes:
  postgres_data:
  pgadmin4_data:
